.TH SLSENDIPV4SOCKET 3 "2026-05-14" "silverlib v1.4.1" "silverlib manual"
.SH NAME
SLSendIPv4Socket - Sends data from a socket
.SH LIBRARY
silverlib library
.SH SYNOPSIS
.nf
.B #define SILVER_LIB_IMPLEMENTATION
.B #include "silverlib.h"

.BI "int SLSendIPv4Socket(int " "sock" ", void* " "data" ", size_t " "size" ", int " "flags" ")"
.fi
.SH DESCRIPTION
Wrapper of the \fBsend\fP(3) function with logging
and errno printing\.
.SH RETURN VALUE
Same return value as \fBsend\fP(3)\.
.SH SEE ALSO
.BR "send" "(3), " "SLInitLib" "(3), " "SLCreateTCPIPv4Socket" "(3), " "SLCloseSocket" "(3), " "SLConnectIPv4Socket" "(3), " "SLListenIPv4Socket" "(3), " "SLRecvIPv4Socket" "(3), "
